name: Waka Readme

on:
  schedule:
    # Runs at 11:47 AM IST (06:17 AM UTC)
    - cron: '17 09 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SECTION_NAME: "waka"
          SHOW_LINES_OF_CODE: "true"
          SHOW_PROJECTS: "true"
          SHOW_SHORT_INFO: "false"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_UPDATED_DATE: "true"
          SHOW_TOTAL_CODE_TIME: "false"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_LOC_CHART: "false"
          SHOW_LANGUAGE: "true"
          SHOW_LANGUAGE_PER_REPO: "true"
          COMMIT_BY_ME: "false"
          COMMIT_MESSAGE: "Updated with Wakatime Metrics"
          COMMIT_SINGLE: "false"
          LOCALE: "en"
